session_name: HookAnchor
start_directory: .
windows:
  - window_name: claude
    panes:
      - shell_command: claude --continue
  - window_name: folder
    panes:
      - shell_command: vim
  - window_name: zsh
    panes:
      - shell_command: zsh
  - window_name: notes
    panes:
      - shell_command: vim "HookAnchor.md"