//! CLI Help Text
//!
//! Functions for displaying help information for the command-line interface.

use crate::utils::print;

/// Print the main help message.
pub fn print_help(_program_name: &str) {
    // Always use "ha" as the program name for cleaner help output
    let name = "ha";
    print("HookAnchor - Universal Command Launcher");
    print("");
    print("Help Topics:");
    print(&format!("  {} -h, --help               # Show this help message", name));
    print(&format!("  {} --help vars              # Template variables ({{{{input}}}}, {{{{date.year}}}}, etc.)", name));
    print(&format!("  {} --help config            # Configuration file structure (YAML)", name));
    print(&format!("  {} --help fns               # JavaScript functions (log, run_command, etc.)", name));
    print("");
    print("Usage:");
    print(&format!("  {} -m, --match <query>      # Search CMDS", name));
    print(&format!("  {} -r, --run_fn <cmd>       # Execute specific CMD", name));
    print(&format!("  {} -x, --execute <query>    # Execute top match", name));
    print(&format!("  {} -p <query>               # Get folder path (first match)", name));
    print(&format!("  {} -P <query>               # Get folder paths (all matches)", name));
    print(&format!("  {} -f <query>               # Get CMD->path (first match)", name));
    print(&format!("  {} -F <query>               # Get CMDS->paths (all matches)", name));
    print(&format!("  {} -c, --command <act> <arg># Test command with action+arg", name));
    print(&format!("  {} -a, --action <name>      # Execute action directly", name));
    print(&format!("  {} -d, --define <params>    # Define new command (n:=NAME a:=ACTION r:=ARG)", name));
    print(&format!("  {} --infer [command]        # Show patch inference changes", name));
    print(&format!("  {} --infer-all              # Show changes and prompt to apply", name));
    print(&format!("  {} --rescan                 # Rescan filesystem with verbose output", name));
    print(&format!("  {} --rebuild                # Rebuild: restart server and rescan filesystem", name));
    print(&format!("  {} --delete-history [--add-commands <path>] [--force] # Delete history and rebuild (optionally from backup)", name));
    print(&format!("  {} --test-grabber           # Test grabber functionality", name));
    print(&format!("  {} --test-permissions       # Test accessibility permissions", name));
    print(&format!("  {} --diagnose               # Full system diagnostics (permissions, signing, server)", name));
    print(&format!("  {} --grab [delay]           # Grab active app after delay", name));
    print(&format!("  {} --start-server           # Force restart command server", name));
    print(&format!("  {} --restart                # Kill and restart command server in new Terminal", name));
    print(&format!("  {} --process-health         # Check for hung processes", name));
    print(&format!("  {} --process-status         # Show detailed process status", name));
    print(&format!("  {} --install                # Run setup assistant (preserves configs)", name));
    print(&format!("  {} --install --force        # Force reinstall (overwrites configs)", name));
    print(&format!("  {} --uninstall              # Uninstall HookAnchor", name));
    print(&format!("  {} --popup                  # Launch popup search interface", name));
    print(&format!("  {} --search                 # Launch history viewer", name));
    print(&format!("  {} --hook <url>             # Handle hook:// URL (for URL handler)", name));
    print(&format!("  {} --load-legacy-and-compare <path> # Load legacy commands and compare", name));
    print("");
    print("URL Schemes (use with 'open' command or browser):");
    print("  hook://QUERY                # Execute command matching QUERY");
    print("  hook://p/[TEXT[/ACTION]]    # Open popup with optional text/action");
    print("  hook://a/ACTION/ARG[?k=v]   # Execute action with optional params");
    print("  hook://f/QUERY              # Open folder of matching command in Finder");
    print("");
    print("Examples:");
    print(&format!("  {} --popup           # Launch popup search interface", name));
    print(&format!("  {} -m spot   # Find 'spot' CMDS", name));
    print(&format!("  {} -x spot   # Execute top 'spot'", name));
    print(&format!("  {} -f spot   # Get 'spot' folders", name));
    print(&format!("  {} -F spo    # Get 'spo' CMDS->paths", name));
    print(&format!("  {} -r Spot   # Execute 'Spot' CMD", name));
}

/// Print help for template variables.
pub fn print_help_vars() {
    print("");
    print("TEMPLATE VARIABLES");
    print("");
    print("These variables are available in two contexts:");
    print("  1. In config.yaml templates using {{variable}} syntax");
    print("  2. In config.js action functions via the ctx object");
    print("");
    print("Command objects with fields (.name .path .arg .patch .folder* .action .flags):");
    print("  selected        Currently selected command in popup");
    print("  last_executed   Last command executed (any type)");
    print("  last_anchor     Last anchor command executed");
    print("");
    print("Date object with fields (.year .year2 .month .month_short .month_name .month_abbr");
    print("                         .day .day_short .weekday .weekday_abbr .hour .hour12");
    print("                         .minute .second .ampm .timestamp .iso):");
    print("  date            Current date/time components");
    print("");
    print("Grab object with fields (.action .arg .app .title .text .suffix):");
    print("  grabbed         Context from active application");
    print("");
    print("Environment object with fields (.home .user .hostname .os .config_dir):");
    print("  env             System environment information");
    print("");
    print("Simple variables:");
    print("  input           User's search input text");
    print("  raw_input       Raw input without anchor fallback");
    print("  arg             Action argument for template expansion");
    print("");
    print("* .folder throws error if empty - use only for commands with file context");
    print("");
    print("YAML Template Examples (in config.yaml):");
    print("  arg: \"{{selected.name}}\"           Command name of selected item");
    print("  arg: \"{{last_executed.folder}}\"    Folder of last command");
    print("  name: \"{{input}}\"                  User's search text");
    print("  arg: \"{{date.year}}-{{date.month}}-{{date.day}}\"  Current date");
    print("");
    print("JavaScript Examples (in config.js action functions):");
    print("  const name = ctx.selected.name;");
    print("  const folder = ctx.last_executed.folder;");
    print("  const input = ctx.input;");
    print("  const year = ctx.date.year;");
    print("");
}

/// Print help for configuration file structure.
pub fn print_help_config() {
    print("");
    print("CONFIGURATION STRUCTURE (~/.config/hookanchor/config.yaml)");
    print("");
    print("popup_settings:");
    print("  # Display & Layout");
    print("  max_rows:               20            # Max rows in popup grid");
    print("  max_columns:            3             # Max columns in popup grid");
    print("  max_characters:         30            # Max length for command names");
    print("  max_window_size:        \"1700x1100\"   # Maximum window size (widthxheight)");
    print("  default_window_size:    \"600x400\"     # Default popup size (widthxheight)");
    print("");
    print("  # Logging & Debug");
    print("  verbose_logging:        false         # Enable detailed logging");
    print("  max_log_file_size:      1000000       # Max log size in bytes (1MB default)");
    print("");
    print("  # Behavior");
    print("  run_in_background:      false         # Keep app running for instant popup");
    print("  merge_similar:          true          # Merge commands ending with \"...\"");
    print("  word_separators:        \" ._-\"        # Characters for word boundaries");
    print("  listed_actions:         \"app,url,folder,cmd,chrome\"  # Editor dropdown");
    print("  preferred_anchor:       \"markdown\"    # Preferred anchor type when multiple exist");
    print("");
    print("  # Timeouts");
    print("  scan_interval_seconds:  600           # Seconds between file scans");
    print("  idle_timeout_seconds:   60            # Seconds before auto-close");
    print("  countdown_seconds:      5             # Grabber countdown duration");
    print("  anchor_timeout_seconds: 180           # Seconds to remember last anchor");
    print("");
    print("  # File Scanning");
    print("  file_roots:             [\"~/path\"]    # Directories to scan");
    print("  doc_file_extensions:    \"pdf,docx\"    # Extensions for DOC commands");
    print("  skip_patterns:                        # Patterns to exclude from scan");
    print("    - \"/pattern/\"");
    print("");
    print("  # Rename Behavior");
    print("  rename_doc:             false         # Rename file when renaming DOC command");
    print("  rename_folder:          false         # Rename folder when renaming anchor");
    print("  rename_patch:           false         # Update all commands with renamed patch");
    print("  rename_prefix:          false         # Update commands with renamed prefix");
    print("");
    print("launcher_settings:");
    print("  js_timeout_ms:          5000          # Max ms for JS action execution");
    print("  obsidian_app_name:      \"Obsidian\"    # Obsidian application name");
    print("  obsidian_vault_name:    \"kmr\"         # Obsidian vault name");
    print("  obsidian_vault_path:    \"~/Documents\" # Path to Obsidian vault");
    print("  flip_focus:             false         # Flip focus during grabber countdown");
    print("  use_javascript_tmux_activation: null  # Use JS for tmux activation");
    print("  tmux_startup_command:   null          # Command to run in tmux after activation");
    print("");
    print("history_viewer:");
    print("  viewable_history_limit: 50000         # Max history entries to load");
    print("  tree_sidebar_width:     250           # Tree sidebar width in pixels");
    print("  tree_sidebar_min_width: 50            # Minimum sidebar width in pixels");
    print("  tree_indent_pixels:     10            # Tree indent per level");
    print("  tree_show_guides:       true          # Show tree indent guide lines");
    print("  peek_on_hover:          true          # Show history on tree item hover");
    print("  key_bindings:");
    print("    edit_selection:       \";\"           # Key to edit selected history item");
    print("");
    print("actions:");
    print("  action_name:                          # Custom action name");
    print("    description:          \"...\"         # What this action does");
    print("    action_type:          template      # Type: template, popup, or custom (calls action_<type>())");
    print("    key:                  \"+\"           # Optional keyboard binding");
    print("    name:                 \"{{input}}\"   # Template for command name");
    print("    action:               \"markdown\"    # Command action type");
    print("    arg:                  \"{{...}}\"     # Template for command argument");
    print("    patch:                \"{{...}}\"     # Template for patch");
    print("    edit:                 true          # Open editor after creation");
    print("    use_existing:         false         # Use existing command if name matches");
    print("    file:                 \"{{...}}\"     # Optional file/folder to create");
    print("    contents:             \"{{...}}\"     # Optional file contents");
    print("    grab:                 5             # Seconds to wait before grabbing");
    print("    validate_previous_folder: false     # Validate previous command has folder");
    print("    file_rescan:          false         # Rescan filesystem after creation");
    print("");
    print("grabber_rules:");
    print("  - app_name:             \"AppName\"     # Application to match");
    print("    action:               \"url\"         # Action type for grabbed content");
    print("    title_contains:       \"pattern\"     # Match window title");
    print("");
    print("grabber_suffix_map:");
    print("  \"@github\":             \"github\\.com\" # Map regex patterns to suffixes");
    print("  \"@docs\":               \"docs\\.google\\.com\"");
    print("");
}

/// Print help for JavaScript functions available in config.js.
pub fn print_help_fns() {
    print("");
    print("FUNCTIONS AVAILABLE FOR \"config.js\" EXTENSIONS");
    print("");
    print("Logging:");
    print("  log(msg)                       Write to log file only");
    print("  print(msg)                     Print to console AND log to file");
    print("  detailedLog(category, msg)     Write msg when verbose_logging is true");
    print("  error(msg)                     Queue error for user display");
    print("");
    print("File System:");
    print("  readFile(path)                 Read text file contents");
    print("  writeFile(path, text)          Write text to file");
    print("  fileExists(path)               Check if file exists (boolean)");
    print("  isDirectory(path)              Check if path is directory (boolean)");
    print("  listFiles(dir, pattern)        List files matching glob pattern");
    print("");
    print("Path Utilities:");
    print("  joinPath(part1, part2)         Join two path components");
    print("  dirname(path)                  Get directory name from path");
    print("  basename(path)                 Get filename from path");
    print("  expandHome(path)               Expand ~ to home directory");
    print("  getExtension(path)             Get file extension");
    print("");
    print("Text and Data Processing:");
    print("  testRegex(text, pattern)       Test if text matches regex (boolean)");
    print("  parseYaml(text)                Parse YAML into JavaScript object");
    print("");
    print("Application Control:");
    print("  launchApp(app, arg?)           Launch app with optional argument");
    print("  openFolder(path)               Open folder in Finder");
    print("  openUrl(url, browser?)         Open URL (optional browser name)");
    print("  activateApp(app_name)          Bring application to foreground");
    print("  appIsRunning(app_name)         Check if app is running (boolean)");
    print("");
    print("Shell Commands:");
    print("  shell(command)                 Execute in background (non-blocking)");
    print("  shellSync(command)             Execute and wait (returns output)");
    print("  shellWithExitCode(cmd)         Returns {stdout, stderr, exitCode}");
    print("  commandExists(command)         Check if command in PATH (boolean)");
    print("  changeDirectory(path)          Change working directory");
    print("  spawnDetached(command)         Spawn detached background process");
    print("  spawnDetachedWithArgs(args)    Spawn with argument array");
    print("");
    print("Other Commands:");
    print("  runAppleScript(script)         Execute AppleScript, return result");
    print("  launch(command_name)           Execute another HookAnchor command");
    print("  saveAnchor(name, folder?)      Save anchor for next popup open");
    print("  getConfigString(path)          Get config value by dot-separated path");
    print("                                 Example: getConfigString(\"launcher_settings.obsidian_vault_path\")");
    print("");
    print("===============================================================================");
    print("CONTEXT OBJECT (for action functions in config.js)");
    print("===============================================================================");
    print("");
    print("  ctx.arg                   Action argument (file path, URL, etc.)");
    print("  ctx.input                 User's search input text");
    print("  ctx.previous.name         Previously executed command name");
    print("  ctx.previous.folder       Previously executed command folder");
    print("  ctx.previous.patch        Previously executed command patch");
    print("  ctx.grabbed.action        Grabbed content action type");
    print("  ctx.grabbed.arg           Grabbed content argument");
    print("  ctx.date.YYYY             Current year (4 digits)");
    print("  ctx.date.MM               Current month (2 digits)");
    print("  ctx.date.DD               Current day (2 digits)");
    print("  ctx.builtins              Object with all built-in functions");
    print("");
    print("Example usage in config.js:");
    print("  action_folder: function(ctx) {");
    print("    const { log, openFolder } = ctx.builtins;");
    print("    openFolder(ctx.arg);");
    print("  }");
    print("");
}
