//! Key parsing and chord handling utilities
//! 
//! Provides functionality to parse key strings in various formats:
//! - ASCII characters: "a", "+", "="
//! - Named keys: "Enter", "Escape", "ArrowUp"
//! - Chord combinations: "Cmd+C", "Ctrl+Shift+A", "Alt+F4"

use std::collections::HashSet;

/// Modifier state for key events
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Modifiers {
    pub ctrl: bool,
    pub alt: bool,
    pub shift: bool,
    pub cmd: bool,
}

impl Modifiers {
    /// Create modifiers with all false
    pub fn none() -> Self {
        Self { ctrl: false, alt: false, shift: false, cmd: false }
    }
    
    /// Create modifiers from egui modifiers
    pub fn from_egui(modifiers: &egui::Modifiers) -> Self {
        Self {
            ctrl: modifiers.ctrl,
            alt: modifiers.alt,
            shift: modifiers.shift,
            cmd: modifiers.command,
        }
    }
}

/// Represents a normalized key event that matches egui's format
/// This can represent either a TEXT event or a KEY event
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum NormalizedKey {
    /// Text event (single character, may have been generated by shifted key)
    Text { 
        char: String,
    },
    /// Key event (key name with modifiers)
    Key { 
        key: String, 
        modifiers: Modifiers 
    },
}

impl NormalizedKey {
    /// Create a text-based normalized key
    pub fn text(char: String) -> Self {
        NormalizedKey::Text { char }
    }
    
    /// Create a key-based normalized key
    pub fn key(key: String, modifiers: Modifiers) -> Self {
        NormalizedKey::Key { key, modifiers }
    }
    
    /// Create a simple key with no modifiers  
    pub fn simple_key(key: String) -> Self {
        NormalizedKey::Key { key, modifiers: Modifiers::none() }
    }
}

/// Convert a config string to a NormalizedKey that matches egui events
/// This is the main function that should be used throughout the codebase
pub fn config_string_to_normalized_key(config_key: &str) -> NormalizedKey {
    // Handle special single characters that generate TEXT events
    let text_chars = [
        "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", 
        "_", "+", "{", "}", "|", ":", "\"", "<", ">", "?", "~"
    ];
    
    if text_chars.contains(&config_key) {
        if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/hookanchor_debug.log") {
            use std::io::Write;
            let _ = writeln!(file, "🔄 Config key '{}' → TEXT event", config_key);
        }
        return NormalizedKey::text(config_key.to_string());
    }
    
    // Handle simple non-shifted characters that also generate TEXT events
    if config_key.len() == 1 && config_key.chars().all(|c| c.is_ascii_alphanumeric() || ",.;'[]\\-=`/".contains(c)) {
        if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/hookanchor_debug.log") {
            use std::io::Write;
            let _ = writeln!(file, "🔄 Config key '{}' → TEXT event (simple char)", config_key);
        }
        return NormalizedKey::text(config_key.to_string());
    }
    
    // Parse as key combination (for KEY events)
    let chord = parse_key_string(config_key);
    let modifiers = Modifiers {
        ctrl: chord.modifiers.contains("Ctrl"),
        alt: chord.modifiers.contains("Alt"),
        shift: chord.modifiers.contains("Shift"),
        cmd: chord.modifiers.contains("Cmd"),
    };
    if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/hookanchor_debug.log") {
        use std::io::Write;
        let _ = writeln!(file, "🔄 Config key '{}' → KEY event: key='{}' modifiers={:?}", config_key, chord.key, modifiers);
    }
    NormalizedKey::key(chord.key, modifiers)
}

/// Convert an egui event to a NormalizedKey for matching
pub fn egui_event_to_normalized_key(event: &egui::Event) -> Option<NormalizedKey> {
    match event {
        egui::Event::Text(text) => {
            if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/hookanchor_debug.log") {
                use std::io::Write;
                let _ = writeln!(file, "📥 egui TEXT event '{}' → NormalizedKey::Text", text);
            }
            Some(NormalizedKey::text(text.clone()))
        },
        egui::Event::Key { key, pressed, modifiers, .. } => {
            if !pressed {
                return None; // Only handle key press events
            }
            
            let key_name = format!("{:?}", key);
            let normalized_modifiers = Modifiers::from_egui(modifiers);
            
            if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/hookanchor_debug.log") {
                use std::io::Write;
                let _ = writeln!(file, "📥 egui KEY event '{}' modifiers={:?} → NormalizedKey::Key", key_name, normalized_modifiers);
            }
            
            Some(NormalizedKey::key(key_name, normalized_modifiers))
        },
        _ => None
    }
}

/// Represents a parsed key combination
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KeyChord {
    /// The main key (without modifiers)
    pub key: String,
    /// Set of modifier keys
    pub modifiers: HashSet<String>,
}

impl KeyChord {
    /// Create a new KeyChord from a key and modifiers
    pub fn new(key: String, modifiers: HashSet<String>) -> Self {
        Self { key, modifiers }
    }
    
    /// Create a simple KeyChord with no modifiers
    pub fn simple(key: String) -> Self {
        Self {
            key,
            modifiers: HashSet::new(),
        }
    }
    
    /// Check if this chord matches the given key event with modifiers
    pub fn matches(&self, key_name: &str, modifiers: &HashSet<String>) -> bool {
        // For direct text matching (when modifiers is empty), also try character-based matching
        if modifiers.is_empty() {
            // First try direct key name matching
            if self.key == key_name && self.modifiers == *modifiers {
                return true;
            }
            
            // For text events, try matching the original config key against the event text
            // This handles cases like config_key="!" matching event_key="!" even though
            // the parsed chord is key="1" modifiers={"Shift"}
            if key_name.len() == 1 {
                // Check if this is a shifted character that should match directly
                let shifted_chars = [
                    ("!", "1"), ("@", "2"), ("#", "3"), ("$", "4"), 
                    ("%", "5"), ("^", "6"), ("&", "7"), ("*", "8"),
                    ("(", "9"), (")", "0"), ("_", "-"), ("+", "="),
                    ("{", "["), ("}", "]"), ("|", "\\"), (":", ";"),
                    ("\"", "'"), ("<", ","), (">", "."), ("?", "/"),
                    ("~", "`")
                ];
                
                for (shifted_char, base_key) in &shifted_chars {
                    if key_name == *shifted_char && self.key == *base_key && self.modifiers.contains("Shift") {
                        if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/hookanchor_debug.log") {
                            use std::io::Write;
                            let _ = writeln!(file, "    ✨ TEXT MATCH: '{}' matches config chord '{}' + Shift", shifted_char, base_key);
                        }
                        return true;
                    }
                }
            }
        }
        
        // Standard matching
        self.key == key_name && self.modifiers == *modifiers
    }
    
    /// Convert back to string representation
    pub fn to_string(&self) -> String {
        if self.modifiers.is_empty() {
            self.key.clone()
        } else {
            let mut parts: Vec<&str> = self.modifiers.iter().map(|s| s.as_str()).collect();
            parts.sort(); // Consistent ordering
            parts.push(&self.key);
            parts.join("+")
        }
    }
}

/// Parse a key string into a KeyChord
/// 
/// Supports formats:
/// - ASCII: "a", "+", "="
/// - Named: "Enter", "Escape" 
/// - Chords: "Cmd+C", "Ctrl+Shift+A", "Cmd+=", "Cmd+Equals"
/// - Special shifted chars: ">" becomes "Shift+Period", "<" becomes "Shift+Comma"
pub fn parse_key_string(key_str: &str) -> KeyChord {
    // Handle special shifted characters first
    match key_str {
        ">" => {
            let mut modifiers = HashSet::new();
            modifiers.insert("Shift".to_string());
            return KeyChord::new("Period".to_string(), modifiers);
        },
        "<" => {
            let mut modifiers = HashSet::new();
            modifiers.insert("Shift".to_string());
            return KeyChord::new("Comma".to_string(), modifiers);
        },
        "!" => {
            let mut modifiers = HashSet::new();
            modifiers.insert("Shift".to_string());
            return KeyChord::new("1".to_string(), modifiers);
        },
        "@" => {
            let mut modifiers = HashSet::new();
            modifiers.insert("Shift".to_string());
            return KeyChord::new("2".to_string(), modifiers);
        },
        "#" => {
            let mut modifiers = HashSet::new();
            modifiers.insert("Shift".to_string());
            return KeyChord::new("3".to_string(), modifiers);
        },
        "^" => {
            let mut modifiers = HashSet::new();
            modifiers.insert("Shift".to_string());
            return KeyChord::new("6".to_string(), modifiers);
        },
        "&" => {
            let mut modifiers = HashSet::new();
            modifiers.insert("Shift".to_string());
            return KeyChord::new("7".to_string(), modifiers);
        },
        _ => {}
    }
    
    // Handle chord notation (contains '+')
    if key_str.contains('+') {
        let parts: Vec<&str> = key_str.split('+').collect();
        if parts.len() < 2 {
            // Malformed chord, treat as simple key
            return KeyChord::simple(normalize_key_name(key_str));
        }
        
        let mut modifiers = HashSet::new();
        let key_part = parts[parts.len() - 1]; // Last part is the key
        
        // All but last part are modifiers
        for modifier in &parts[..parts.len() - 1] {
            let normalized_modifier = normalize_modifier(modifier);
            modifiers.insert(normalized_modifier);
        }
        
        // Handle special case where key part is a shifted character
        let (final_key, additional_modifiers) = match key_part {
            ">" => ("Period".to_string(), vec!["Shift".to_string()]),
            "<" => ("Comma".to_string(), vec!["Shift".to_string()]),
            "!" => ("1".to_string(), vec!["Shift".to_string()]),
            "@" => ("2".to_string(), vec!["Shift".to_string()]),
            "#" => ("3".to_string(), vec!["Shift".to_string()]),
            "^" => ("6".to_string(), vec!["Shift".to_string()]),
            "&" => ("7".to_string(), vec!["Shift".to_string()]),
            _ => (normalize_key_name(key_part), vec![]),
        };
        
        // Add any additional modifiers from shifted characters
        for additional_mod in additional_modifiers {
            modifiers.insert(additional_mod);
        }
        
        KeyChord::new(final_key, modifiers)
    } else {
        // Simple key (no modifiers) - normalize ASCII characters
        KeyChord::simple(normalize_key_name(key_str))
    }
}

/// Normalize modifier key names to standard forms
fn normalize_modifier(modifier: &str) -> String {
    match modifier.to_lowercase().as_str() {
        // Command key (Mac)
        "cmd" | "command" | "meta" => "Cmd".to_string(),
        // Control key
        "ctrl" | "control" => "Ctrl".to_string(),
        // Alt/Option key
        "alt" | "option" | "opt" => "Alt".to_string(),
        // Shift key
        "shift" => "Shift".to_string(),
        // Pass through unknown modifiers as-is
        _ => modifier.to_string(),
    }
}

/// Check if a key event with modifiers matches a key configuration string
pub fn key_matches(config_key: &str, event_key: &str, event_modifiers: &HashSet<String>) -> bool {
    // Debug logging for key matching
    if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/hookanchor_debug.log") {
        use std::io::Write;
        let _ = writeln!(file, "    🔍 key_matches: config_key='{}' event_key='{}' event_modifiers={:?}", 
            config_key, event_key, event_modifiers);
    }
    
    let chord = parse_key_string(config_key);
    
    if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/hookanchor_debug.log") {
        use std::io::Write;
        let _ = writeln!(file, "    📊 Parsed chord: key='{}' modifiers={:?}", chord.key, chord.modifiers);
    }
    
    let result = chord.matches(event_key, event_modifiers);
    
    if let Ok(mut file) = std::fs::OpenOptions::new().create(true).append(true).open("/tmp/hookanchor_debug.log") {
        use std::io::Write;
        let _ = writeln!(file, "    🎯 Match result: {}", result);
    }
    
    result
}

/// Normalize key names to handle both ASCII characters and word names
/// 
/// This allows users to write either "/" or "Slash", "=" or "Equals", etc.
/// Both forms will be converted to the egui standard name.
pub fn normalize_key_name(key: &str) -> String {
    match key {
        // ASCII characters -> egui key names
        "-" => "Minus".to_string(),
        "=" => "Equals".to_string(),
        "+" => "Plus".to_string(),
        "/" => "Slash".to_string(),
        "\\" => "Backslash".to_string(),
        ";" => "Semicolon".to_string(),
        "`" => "Backtick".to_string(),
        "," => "Comma".to_string(),
        "." => "Period".to_string(),
        " " => "Space".to_string(),
        ":" => "Colon".to_string(),
        "|" => "Pipe".to_string(),
        "?" => "Questionmark".to_string(),
        "!" => "Exclamationmark".to_string(),
        "'" => "Quote".to_string(),
        "@" => "At".to_string(),
        "#" => "Hash".to_string(),
        "^" => "Caret".to_string(),
        "&" => "Ampersand".to_string(),
        
        // Word names that should pass through unchanged (already correct)
        "Minus" | "Equals" | "Plus" | "Slash" | "Backslash" | "Semicolon" |
        "Backtick" | "Comma" | "Period" | "Space" | "Colon" | "Pipe" |
        "Questionmark" | "Exclamationmark" | "Quote" | "At" | "Hash" | "Caret" | "Ampersand" => key.to_string(),
        
        // Arrow keys
        "ArrowUp" | "ArrowDown" | "ArrowLeft" | "ArrowRight" => key.to_string(),
        
        // Control keys
        "Escape" | "Enter" | "Tab" | "Backspace" | "Delete" | "Insert" |
        "Home" | "End" | "PageUp" | "PageDown" => key.to_string(),
        
        // Function keys
        key if key.starts_with('F') && key[1..].parse::<u8>().is_ok() => key.to_string(),
        
        // Letters and numbers - uppercase for consistency
        c if c.len() == 1 && c.chars().next().unwrap().is_ascii_alphabetic() => c.to_uppercase(),
        c if c.len() == 1 && c.chars().next().unwrap().is_ascii_digit() => c.to_string(),
        
        // Everything else passes through unchanged
        _ => key.to_string(),
    }
}

/// Convert ASCII character to standard key name for compatibility
/// 
/// This is now a wrapper around normalize_key_name for backwards compatibility
pub fn ascii_to_key_name(ascii_char: &str) -> String {
    normalize_key_name(ascii_char)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_simple_key() {
        let chord = parse_key_string("a");
        assert_eq!(chord.key, "A"); // Now normalized to uppercase
        assert!(chord.modifiers.is_empty());
    }

    #[test]
    fn test_parse_ascii_symbols() {
        let chord = parse_key_string("-");
        assert_eq!(chord.key, "Minus"); // Now normalized to word name
        assert!(chord.modifiers.is_empty());
        
        let chord = parse_key_string("=");
        assert_eq!(chord.key, "Equals"); // Now normalized to word name
        assert!(chord.modifiers.is_empty());
    }

    #[test]
    fn test_parse_chord_keys() {
        let chord = parse_key_string("Cmd+C");
        assert_eq!(chord.key, "C");
        assert!(chord.modifiers.contains("Cmd"));
        assert_eq!(chord.modifiers.len(), 1);
    }

    #[test]
    fn test_parse_multiple_modifiers() {
        let chord = parse_key_string("Ctrl+Shift+A");
        assert_eq!(chord.key, "A");
        assert!(chord.modifiers.contains("Ctrl"));
        assert!(chord.modifiers.contains("Shift"));
        assert_eq!(chord.modifiers.len(), 2);
    }

    #[test]
    fn test_normalize_modifiers() {
        assert_eq!(normalize_modifier("cmd"), "Cmd");
        assert_eq!(normalize_modifier("CTRL"), "Ctrl");
        assert_eq!(normalize_modifier("alt"), "Alt");
        assert_eq!(normalize_modifier("shift"), "Shift");
    }

    #[test]
    fn test_key_matches() {
        let mut modifiers = HashSet::new();
        modifiers.insert("Cmd".to_string());
        
        assert!(key_matches("Cmd+C", "C", &modifiers));
        assert!(!key_matches("Cmd+C", "C", &HashSet::new()));
        assert!(key_matches("a", "A", &HashSet::new())); // Key gets normalized to uppercase
    }

    #[test]
    fn test_chord_to_string() {
        let mut modifiers = HashSet::new();
        modifiers.insert("Cmd".to_string());
        modifiers.insert("Shift".to_string());
        
        let chord = KeyChord::new("A".to_string(), modifiers);
        let string_repr = chord.to_string();
        
        // Should contain all parts (order may vary due to HashSet)
        assert!(string_repr.contains("Cmd"));
        assert!(string_repr.contains("Shift"));
        assert!(string_repr.contains("A"));
        assert!(string_repr.contains("+"));
    }

    #[test]
    fn test_normalize_key_name() {
        // ASCII characters should be normalized to word names
        assert_eq!(normalize_key_name("-"), "Minus");
        assert_eq!(normalize_key_name("="), "Equals");
        assert_eq!(normalize_key_name("+"), "Plus");
        assert_eq!(normalize_key_name("/"), "Slash");
        assert_eq!(normalize_key_name(";"), "Semicolon");
        assert_eq!(normalize_key_name("`"), "Backtick");
        
        // Word names should pass through unchanged
        assert_eq!(normalize_key_name("Minus"), "Minus");
        assert_eq!(normalize_key_name("Equals"), "Equals");
        assert_eq!(normalize_key_name("ArrowUp"), "ArrowUp");
        assert_eq!(normalize_key_name("Enter"), "Enter");
        
        // Letters should be uppercase
        assert_eq!(normalize_key_name("a"), "A");
        assert_eq!(normalize_key_name("z"), "Z");
        
        // Numbers should pass through
        assert_eq!(normalize_key_name("1"), "1");
        assert_eq!(normalize_key_name("0"), "0");
    }

    #[test]
    fn test_parse_ascii_keys_in_chords() {
        // Test ASCII characters in chord combinations
        let chord = parse_key_string("Cmd+=");
        assert_eq!(chord.key, "Equals");
        assert!(chord.modifiers.contains("Cmd"));
        
        let chord = parse_key_string("Ctrl+/");
        assert_eq!(chord.key, "Slash");
        assert!(chord.modifiers.contains("Ctrl"));
        
        let chord = parse_key_string("Alt+-");
        assert_eq!(chord.key, "Minus");
        assert!(chord.modifiers.contains("Alt"));
    }

    #[test]
    fn test_parse_word_keys_in_chords() {
        // Test word names in chord combinations
        let chord = parse_key_string("Cmd+Equals");
        assert_eq!(chord.key, "Equals");
        assert!(chord.modifiers.contains("Cmd"));
        
        let chord = parse_key_string("Ctrl+Slash");
        assert_eq!(chord.key, "Slash");
        assert!(chord.modifiers.contains("Ctrl"));
    }

    #[test]
    fn test_parse_special_shifted_characters() {
        // Test that ">" becomes "Shift+Period"
        let chord = parse_key_string(">");
        assert_eq!(chord.key, "Period");
        assert!(chord.modifiers.contains("Shift"));
        assert_eq!(chord.modifiers.len(), 1);
        
        // Test that "<" becomes "Shift+Comma"
        let chord = parse_key_string("<");
        assert_eq!(chord.key, "Comma");
        assert!(chord.modifiers.contains("Shift"));
        assert_eq!(chord.modifiers.len(), 1);
        
        // Test that "!" becomes "Shift+1"
        let chord = parse_key_string("!");
        assert_eq!(chord.key, "1");
        assert!(chord.modifiers.contains("Shift"));
        assert_eq!(chord.modifiers.len(), 1);
        
        // Test that "Cmd+>" becomes "Cmd+Shift+Period"
        let chord = parse_key_string("Cmd+>");
        assert_eq!(chord.key, "Period");
        assert!(chord.modifiers.contains("Cmd"));
        assert!(chord.modifiers.contains("Shift"));
        assert_eq!(chord.modifiers.len(), 2);
    }

    #[test]
    fn test_key_matches_with_ascii_and_word_names() {
        let mut modifiers = HashSet::new();
        modifiers.insert("Cmd".to_string());
        
        // Both ASCII and word name should match
        assert!(key_matches("Cmd+=", "Equals", &modifiers));
        assert!(key_matches("Cmd+Equals", "Equals", &modifiers));
        
        // Test simple keys
        assert!(key_matches("/", "Slash", &HashSet::new()));
        assert!(key_matches("Slash", "Slash", &HashSet::new()));
    }
}