#!/usr/bin/env python3
"""
Generate default_config.yaml from personal config by replacing personal paths with defaults.

This script creates a clean default configuration from the user's personal config,
replacing personal paths and settings with generic defaults suitable for new users.
"""

import sys
import os
import re
from pathlib import Path

def generate_default_config():
    """Generate default_config.yaml from personal config with generic defaults."""
    
    # Paths
    personal_config = Path.home() / ".config" / "hookanchor" / "config.yaml"
    project_root = Path(__file__).parent.parent
    output_file = project_root / "resources" / "common" / "default_config.yaml"
    
    if not personal_config.exists():
        print(f"ERROR: Personal config not found at {personal_config}")
        return False
    
    print(f"Reading personal config from: {personal_config}")
    
    # Read personal config
    with open(personal_config, 'r') as f:
        content = f.read()
    
    # Replace personal paths with generic defaults
    replacements = [
        # Markdown roots - replace with generic defaults
        (r'markdown_roots:\n - "~/ob/kmr"\n - "~/Documents"\n - "~/Notes"', 
         'markdown_roots:\n - "~/Documents"\n - "~/Notes"'),
        
        # Obsidian settings - replace personal vault with generic
        (r'obsidian_vault_name:\s*"kmr"', 'obsidian_vault_name: "MyVault"'),
        (r'obsidian_vault_path:\s*"~/ob/kmr"', 'obsidian_vault_path: "~/Documents"'),
        
        # Scanner settings - replace personal orphans path
        (r'orphans_path:\s*"/Users/oblinger/ob/kmr/SYS/Closet/Orphans"', 
         'orphans_path: "~/Documents/Orphans"'),
        
        # Templates - replace personal paths in note template
        (r'arg: "~/ob/kmr/Notes/{{YYYY}}/{{MM}}/{{YYYY}}-{{MM}}-{{DD}} {{input}}.md"', 
         'arg: "~/Notes/{{YYYY}}/{{MM}}/{{YYYY}}-{{MM}}-{{DD}} {{input}}.md"'),
        (r'file: "~/ob/kmr/Notes/{{YYYY}}/{{MM}}"', 
         'file: "~/Notes/{{YYYY}}/{{MM}}"'),
        
        # Functions - replace vault reference in action_obs
        (r"vault=kmr&file", "vault=MyVault&file"),
    ]
    
    # Apply replacements
    for pattern, replacement in replacements:
        content = re.sub(pattern, replacement, content)
    
    # Clean up any empty lines from removals
    content = re.sub(r'\n\s*\n\s*\n', '\n\n', content)
    
    # Add header comment
    header = """# HookAnchor Default Configuration
# 
# This file is automatically generated from the developer's personal config.
# Personal paths have been replaced with generic defaults suitable for new users.
# 
# Copy this to ~/.config/hookanchor/config.yaml and customize as needed.

"""
    
    content = header + content
    
    # Ensure output directory exists
    output_file.parent.mkdir(parents=True, exist_ok=True)
    
    # Write default config
    print(f"Writing default config to: {output_file}")
    with open(output_file, 'w') as f:
        f.write(content)
    
    print("✅ Default config generated successfully!")
    return True


if __name__ == "__main__":
    success = generate_default_config()
    sys.exit(0 if success else 1)